# Generated by Django 3.1.3 on 2020-11-21 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0003_auto_20201121_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='Post_comments', to='Posts.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='Post_hearts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
