# Generated by Django 3.1.3 on 2020-11-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20201121_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
