# Generated by Django 3.1.3 on 2020-11-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(choices=[('Report bugs', 'Report bugs'), ('Report posts', 'Report posts'), ('Report security issues', 'Report security issues'), ('Help for projects', 'Help for projects'), ('For business', 'For business'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
