# Generated by Django 3.1.3 on 2020-11-22 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0005_auto_20201121_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=350, null=True)),
                ('story_pic', models.ImageField(blank=True, null=True, upload_to='story_pics')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('show_email_to_public', models.BooleanField(default=True)),
                ('show_names_to_public', models.BooleanField(default=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='user_bookmarks', to='Posts.Post')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
