# Generated by Django 3.1.3 on 2020-11-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
