# Generated by Django 3.1.3 on 2020-11-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20201123_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Avatar_4_kbds1n.png', upload_to='profile_pics'),
        ),
    ]
