# Generated by Django 3.1.3 on 2020-11-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
    ]
