# Generated by Django 3.1.3 on 2020-11-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_auto_20201125_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='story_pics',
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_pics',
            field=models.ImageField(default='Banner_tnqth0.jpg', upload_to='banner_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Avatar_1_d3tcxq.png', upload_to='profile_pics'),
        ),
    ]
